"""Add validation_status and last_validated to datasets table

Revision ID: 3ffb616baf27
Revises: 95b90f8d6778
Create Date: 2025-10-26 18:26:12.862468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffb616baf27'
down_revision: Union[str, Sequence[str], None] = '95b90f8d6778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to datasets table
    op.add_column('datasets', sa.Column('validation_status', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove new columns from datasets table
    op.drop_column('datasets', 'last_validated')
    op.drop_column('datasets', 'validation_status')
    # ### end Alembic commands ###
