"""add status to users and create templates table

Revision ID: 700f2c757832
Revises: 9eaa23680b9c
Create Date: 2025-10-06 21:48:42.964897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700f2c757832'
down_revision: Union[str, Sequence[str], None] = '9eaa23680b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=True, server_default='active'))
    op.execute("UPDATE users SET status='active' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_table('templates')
    # ### end Alembic commands ###
