"""add_lineage_eda_drift_tables

Revision ID: adf3e12a8c40
Revises: 038bb1ab2fb2
Create Date: 2026-06-18 14:15:26.192831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf3e12a8c40'
down_revision: Union[str, Sequence[str], None] = '038bb1ab2fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_lineages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('input_storage_key', sa.String(), nullable=True),
    sa.Column('output_storage_key', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eda_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('summary_metrics', sa.JSON(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('outliers_json', sa.JSON(), nullable=True),
    sa.Column('correlations_json', sa.JSON(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_drift_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_drifted', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_metas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_drift_metrics')
    op.drop_table('eda_reports')
    op.drop_table('data_lineages')
    # ### end Alembic commands ###

